// Copyright (c) 2026, Yakov Usoltsev
// Email: yakovmen62@gmail.com
//
// License: MIT

#include "example.hpp"
#include "schema_example.hpp"

#include <iostream>

void simple_schema_example() {
    rapidjson::Document doc;
    doc.SetObject();

    macrojson::generate_schema<SimpleExample>(
        nullptr, "A simple example object", "This is a simple example of a JSON schema generated by MacroJSON.",
        doc.GetAllocator(), doc);

    rapidjson::StringBuffer buffer;
    rapidjson::Writer<rapidjson::StringBuffer> writer(buffer);
    doc.Accept(writer);

    std::cout << "simple_schema_example" << std::endl;
    std::cout << "Generated JSON Schema:" << std::endl;
    std::cout << buffer.GetString() << std::endl;
    std::cout << std::endl;
}

